services:
  postgres:
    image: postgres:18
    container_name: adonis_postgres
    environment:
      POSTGRES_USER: process.env.PG_USER
      POSTGRES_PASSWORD: process.env.PG_PASSWORD
      POSTGRES_DB: process.env.PG_DB_NAME
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    restart: unless-stopped

volumes:
  pgdata:
